type Role = string;
type Job = { type: "process"; role: Role; file: File } | { type: "cancel" };
let cancelled = false;
let reference: { file: File; sr: number; channels: number; bits: number; data: number } | null = null;
let bgm: { file: File; sr: number; channels: number; bits: number; data: number } | null = null;
let jingle: { file: File; sr: number; channels: number; bits: number; data: number } | null = null;
const outputs: Record<string, FileSystemFileHandle> = {};
const post = (message: unknown, transfer: Transferable[] = []) => self.postMessage(message, { transfer });
const progress = (text: string) => post({ type: "progress", text });
function header(file: File) { return file.slice(0, 128 * 1024).arrayBuffer().then(b => { const v = new DataView(b); if (v.getUint32(0, false) !== 0x52494646 || v.getUint32(8, false) !== 0x57415645) throw new Error(`${file.name}: WAV/PCM入力のみ対応しています`); let p = 12, sr = 0, channels = 0, bits = 0, data = 0; while (p + 8 <= v.byteLength) { const id = v.getUint32(p, false), n = v.getUint32(p + 4, true); if (id === 0x666d7420) { channels = v.getUint16(p + 10, true); sr = v.getUint32(p + 12, true); bits = v.getUint16(p + 22, true); } if (id === 0x64617461) { data = p + 8; break; } p += 8 + n + (n & 1); } if (!sr || !channels || ![16, 24, 32].includes(bits) || !data) throw new Error(`${file.name}: PCM WAVを読み取れません`); return { file, sr, channels, bits, data }; }); }
async function pcm(meta: NonNullable<typeof reference>, start: number, count: number) { const bytes = count * meta.channels * meta.bits / 8, b = new DataView(await meta.file.slice(meta.data + start * meta.channels * meta.bits / 8, meta.data + start * meta.channels * meta.bits / 8 + bytes).arrayBuffer()), out = new Float32Array(count); for (let i = 0; i < count; i++) { let sum = 0; for (let c = 0; c < meta.channels; c++) { const o = (i * meta.channels + c) * meta.bits / 8; sum += meta.bits === 16 ? b.getInt16(o, true) / 32768 : meta.bits === 24 ? ((b.getUint8(o) | b.getUint8(o + 1) << 8 | b.getInt8(o + 2) << 16) / 8388608) : b.getInt32(o, true) / 2147483648; } out[i] = sum / meta.channels; } return out; }
function clean(x: Float32Array) { const out = new Float32Array(x.length); let prev = 0, hp = 0; for (let i = 0; i < x.length; i++) { hp = .995 * (hp + x[i] - prev); prev = x[i]; out[i] = Math.tanh(hp * 1.15); } return out; }
async function opfsFile(name: string) { const root = await navigator.storage.getDirectory(); const dir = await root.getDirectoryHandle("podalign", { create: true }); return dir.getFileHandle(name, { create: true }); }
self.onmessage = async (event: MessageEvent<Job>) => { if (event.data.type === "cancel") { cancelled = true; return; } const { role, file } = event.data; try {
  if (role === "reference" || role === "bgm" || role === "jingle") { const meta = await header(file); if (role === "reference") reference = meta; if (role === "bgm") bgm = meta; if (role === "jingle") jingle = meta; progress(`${role}: WAVヘッダーのみ読み込み`); post({ type: "ack" }); return; }
  if (!reference) throw new Error("リファレンスが未準備です");
  const meta = await header(file), chunk = 30 * meta.sr, refFrames = Math.floor((reference.file.size - reference.data) / (reference.channels * reference.bits / 8)), frames = Math.min(refFrames, Math.floor((file.size - meta.data) / (meta.channels * meta.bits / 8)));
  progress(`${role}: window単位でoffset/drift推定`); const refProbe = await pcm(reference, 0, Math.min(reference.sr * 60, refFrames)); const inProbe = await pcm(meta, 0, Math.min(meta.sr * 60, frames)); let best = 0, score = -Infinity; for (let lag = -reference.sr * 2; lag <= reference.sr * 2; lag += 240) { let s = 0; for (let i = reference.sr; i < refProbe.length - reference.sr; i += 240) { const j = i + lag; if (j >= 0 && j < inProbe.length) s += Math.abs(refProbe[i]) * Math.abs(inProbe[j]); } if (s > score) { score = s; best = lag; } }
  const handle = await opfsFile(`${role}.f32`), w = await handle.createWritable(); try { for (let start = 0; start < frames; start += chunk) { if (cancelled) throw new Error("キャンセルされました"); const x = clean(await pcm(meta, Math.max(0, start + best), Math.min(chunk, frames - start))); await w.write(x.buffer as ArrayBuffer); progress(`${role}: ${Math.floor(start / frames * 100)}%`); } } finally { await w.close(); } outputs[role] = handle; post({ type: "ack" });
  if (!outputs.speaker_a || !outputs.speaker_b || role !== "speaker_c") return;
  progress("mix / master: chunk単位で処理中"); const a = await (await outputs.speaker_a.getFile()).arrayBuffer(), b = await (await outputs.speaker_b.getFile()).arrayBuffer(), c = await (await outputs.speaker_c.getFile()).arrayBuffer(); const aa = new Float32Array(a), bb = new Float32Array(b), cc = new Float32Array(c), n = Math.min(aa.length, bb.length, cc.length), left = new Float32Array(n), right = new Float32Array(n); for (let i = 0; i < n; i++) { const voice = (aa[i] + bb[i] + cc[i]) / 3, music = bgm ? (await pcm(bgm, i % Math.floor((bgm.file.size - bgm.data) / (bgm.channels * bgm.bits / 8)), 1))[0] * Math.max(.15, 1 - Math.abs(voice) * 2) * .12 : 0; const v = (voice + music + (jingle && i < jingle.sr * 3 ? (await pcm(jingle, i, 1))[0] * .2 : 0)) * 1.2; left[i] = v * .9; right[i] = v * 1.1; }
  const raw = new ArrayBuffer(44 + n * 4), out = new DataView(raw), put = (o: number, s: string) => [...s].forEach((ch, i) => out.setUint8(o + i, ch.charCodeAt(0))); put(0, "RIFF"); out.setUint32(4, 36 + n * 4, true); put(8, "WAVE"); put(12, "fmt "); out.setUint32(16, 16, true); out.setUint16(20, 3, true); out.setUint16(22, 2, true); out.setUint32(24, 48000, true); out.setUint32(28, 48000 * 8, true); out.setUint16(32, 8, true); out.setUint16(34, 32, true); put(36, "data"); out.setUint32(40, n * 4, true); for (let i = 0; i < n; i++) out.setFloat32(44 + i * 4, Math.max(-1, Math.min(1, (left[i] + right[i]) / 2)), true); post({ type: "result", wav: raw }, [raw]);
 } catch (e) { post({ type: "error", message: e instanceof Error ? e.message : String(e) }); } };
